apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  replicas: 1
  selector: #these are to select pod
    matchLabels:
      project: roboshop
      component: frontend
      tier: frontend
  template: #this info belongs to container/pod definition
    metadata:
      labels:
        project: roboshop
        component: frontend
        tier: frontend  
    spec:
      containers:
      - name: frontend
        image: pravakula/frontend:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: frontend
        ports:
        - name: liveness-port
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  

 
