apiVersion: v1  
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_PORT: "8080"
  CART_HOST: "cart"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: backend
spec:
  replicas: 1
  selector: #these are to select pod
    matchLabels:
      project: roboshop
      component: payment
      tier: backend
  template: #this info belongs to container/pod definition
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: backend  
    spec:
      containers:
      - name: payment
        image: pravakula/payment:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: payment
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  

 
