apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rabbitmq
  namespace: roboshop
  labels: #these labels are for deployment
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: #these are used to select pods
      project: roboshop
      component: rabbitmq
      tier: db
  template: 
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector: 
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
   - protocol: TCP
     port: 5672
     targetPort: 5672