apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: roboshop
  labels: #these labels are for deployment
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: #these are used to select pods
      project: roboshop
      component: mysql
      tier: db
  template: 
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: pravakula/mysql:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector: 
    project: roboshop
    component: mysql
    tier: db
  ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306