apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector: #these are to select pod
    matchLabels:
      project: roboshop
      component: catalogue
      tier: backend
  template: #this info belongs to container/pod definition
    metadata:
      labels:
        project: roboshop
        component: catalogue
        tier: backend  
    spec:
      containers:
      - name: catalogue
        image: pravakula/catalogue:v1
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  

 
