apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
  namespace: roboshop
  labels: #these labels are for deployment
    project: roboshop
    component: redis
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: #these are used to select pods
      project: roboshop
      component: redis
      tier: db
  template: 
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector: 
    project: roboshop
    component: redis
    tier: db
  ports:
   - protocol: TCP
     port: 6379
     targetPort: 6379

